# Generated by Django 5.2 on 2025-04-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_post2_content_post2_likes_remove_post2_dislikes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
